#Esse workflow irá buildar um projeto maven utilizando kafka e cucumber

name: Integration Test (KafkaTest)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install docker compose
        run: sudo su

      - name: Install docker compose parte 2
        run: sudo curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose

      - name: application persmission docker compose
        run: sudo chmod +x /usr/local/bin/docker-compose;

      - name: verify version docker compose
        run: docker-compose --version

      - name: Start containers
        run: docker-compose up

      - name: Run tests
        run: mvn test -B package --file pom.xml